import { Check, CreditCard, Facebook } from "lucide-react";
import { type NextPage } from "next";

import Head from "next/head";

import { Button } from "~/components/ui/button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1 className="mb-10 text-4xl font-bold">Primary Buttons</h1>

        <Button size="lg">Order Now</Button>
      </div>
    </>
  );
};

export default Home;
